# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SeanBE
tagline:          'The Software Engineer'
description:      'Blog of Sean Löfgren'
url:              http://seanBE.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          0.0.1
