title: "Sean Löfgren"
disqusShortname: "seanBE"
googleAnalytics: "UA-65235616-1"
baseURL: "https://seanBE.github.io/"
disableKinds: ["taxonomy", "taxonomyTerm"]

languageCode: en
DefaultContentLanguage: en

author:
    name: "Sean Löfgren"

params:
    github: SeanBE
    twitter: seanBE
    gitlab: SeanBE
    linkedin: seanlofgren
    logofile: /img/avatar.jpeg
    faviconfile: /img/favicon.ico
    description: "The Blog of Sean Löfgren"
