baseurl: "https://seanBE.github.io/"
languageCode: "en"
title: "Sean Löfgren"
disqusShortname: "seanBE"
googleAnalytics: "UA-65235616-1"
theme: "cocoa-eh"

params:
    name: "Sean Löfgren"
    description: "The Blog of Sean Löfgren"
    logofile: "images/avatar.png"
    faviconfile: "images/favicon.ico"
    highlightjs: true

social:
    twitter: "https://www.twitter.com/seanBE"
    github: "https://github.com/SeanBE"
    linkedin: "https://www.linkedin.com/in/seanlofgren"
