baseurl: "http://seanBE.github.io"
languageCode: "en-us"
title: "Sean Löfgren"
theme: slim
permalinks:
  post: /:slug/

params:
  Subtitle: "Software engineer/Data Scientist in the making."
  GithubID: "seanBE"
  TwitterID: "seanBE"
  AnalyticsID: "UA-65235616-1"
  LinkedInID: "seanlofgren"
  Content: true
