title: "Sean Löfgren"
disqusShortname: "seanBE"
googleAnalytics: "UA-65235616-1"
baseURL: "https://slofgren.com/"
disableKinds: ["taxonomy", "taxonomyTerm", "section"]

languageCode: en
DefaultContentLanguage: en

author:
    name: "Sean Löfgren"

params:
    github: SeanBE
    twitter: seanBE
    gitlab: SeanBE
    linkedin: seanlofgren
    faviconfile: /img/favicon.ico
    description: "The Blog of Sean Löfgren"
