baseurl: "http://seanBE.github.io/"
languageCode: "en-us"
title: "The Blog of Sean Löfgren"
disqusShortname: "seanBE"

params:
    name: "Sean Löfgren"
    bio: "Software engineer - Data Scientist"
    googleAnalytics: "UA-65235616-1"

social:
    twitter: "https://www.twitter.com/seanBE"
    github: "https://github.com/SeanBE"
    linkedin-square: "https://www.linkedin.com/in/seanlofgren"
